### ISSUE TITLE
Now needs explicit dependency on magit-popup

### ISSUE THREAD

**Issue by aspiers** [somtin/magit-gerrit#1]
As per terranpro/magit-gerrit#62 and magit/magit#3877, magit no longer depends on magit-popup, so the latter gets removed during an upgrade to newer magits. This breaks magit-gerrit which depends on magit-popup without explicitly declaring that dependency.

**Comment by somtin** [comment]
Fixed in 1cbc921b98e2a4a4fe67d5f4f09a8bf1fc210a16
